### ISSUE TITLE
plug screendoor form to website

### ISSUE THREAD

**Issue by claudioccm** [govlabacademy/govlabacademy.github.io#103]
I need admin permission to start working on the embed thing

**Comment by claudioccm** [comment]
@dino-at-thegovlab

**Comment by claudioccm** [comment]
@sahuguet - I am trying to embed the form in our page, but I am not really understanding what's wrong. They have 2 ways to embed the form. iFrame and FormRenderer. 
You need screendoor admin user to access this url (dinorah can give you that): 
https://screendoor.dobt.co/the-govlab/coaching-programs-application-form/admin/embed_code

I can make iFrame work, but I can't style the form elements. This is a CSS limitation. 

So I need to embed it using this FormRenderer JS library. I tried it, followed the instructions, etc. No success. Whenever you can help me with that, it would be great. Thanks.

**Comment by dino-at-thegovlab** [comment]
Hey, you have admin access :/ is it not working?

**Comment by claudioccm** [comment]
I have. I am asking for Arnaud's help on this. Things aren't as straight
forward as I thought they would be. He will also need Admin access to
screendoor

**Comment by dino-at-thegovlab** [comment]
You can also ask joshua

**Comment by dino-at-thegovlab** [comment]
@claudioccm what's the status of this issue? Do you want me to connect you to Josh or do you need @sahuguet help?

**Comment by claudioccm** [comment]
if Arnaud can make the FormRendered JS work for me, it would be better, cause it would take the "making it render" problem out of my shoulder. Then I can jump in to style the forms. Makes sense?

**Comment by sahuguet** [comment]
Where do you want the form to appear?
Which page?

**Comment by sahuguet** [comment]
Fixed.
We had to upgrade to a newer version.
I have added the form for each program and in the sandbox.
