### ISSUE TITLE
Home button - please do not send people to different places

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#108]
I think it is confusing that, if clicked on govlab people are sent to the general govlab webpage... and then if clicked academy, people are send home. 

Logo is seen as together so please, make it only for if clicked people go to home.

**Comment by claudioccm** [comment]
@dino-at-thegovlab 
I agree with you. This was Beth's request. I don't think we should change it without her approval. 
I wouldn't bring this up before Launch though. 
Also, this was brought up by Stefaan. So it's up to you if you want to get into this fight. I wouldn't.

**Comment by dino-at-thegovlab** [comment]
Hey. We need to fix this. Already talked to Beth and what they want is for somewhere, people get sent to the govlab general webpage but, doing it from what intuitively is the home button, is not an option. 

Hyperlink the about, about the govlab, etc... but not the home button.
