### ISSUE TITLE
FAQ button for each of the coaching programs

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#121]
Not working

@sahuguet can you fix it?

**Comment by sahuguet** [comment]
works for me.
On the main coaching program page and from individual program pages.

On Tue, Mar 3, 2015 at 3:57 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> Not working
> 
> @sahuguet https://github.com/sahuguet can you fix it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/academy/issues/121.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by dino-at-thegovlab** [comment]
Doesn't work for: 
- open contracting
- Open Data Data-Driven Decisions for All
- Lab Design: Bringing Agility and Empiricism to Public Problems
- Open Source Technology Practices For Civic Engagement Projects

**Comment by sahuguet** [comment]
fixed.

On Tue, Mar 3, 2015 at 4:19 PM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> Doesn't work for:
> - open contracting
> - Open Data Data-Driven Decisions for All
> - Lab Design: Bringing Agility and Empiricism to Public Problems
> - Open Source Technology Practices For Civic Engagement Projects
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/academy/issues/121#issuecomment-77036697.

## 

Arnaud Sahuguet
– Chief Technology Officer
