### ISSUE TITLE
coaching programs course list

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#21]
Please add to each coaching program on the list that shows at the landpage:
Course begins: date
Application due: date

Maybe to the left of where faculty shows

**Comment by dino-at-thegovlab** [comment]
Also, programs should be displayed by dates, starting with the ones that will begin first, etc. (FAQ's section has them in that order)

**Comment by claudioccm** [comment]
done
