### ISSUE TITLE
coaching programs - faculty

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#22]
I'm not sure, design-wise, the faculty shown in the box, helps or just makes it look weird and for most courses, with too much blank spaces

but we should also consider that below, a section with the week-to-week will be added so, don't know... just wanted to share the concern

**Comment by claudioccm** [comment]
I didn't understand this. Let's leave this way, and whenever we need to add more content in these pages, we will figure this out
