### ISSUE TITLE
coaching programs - individual pages

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#24]
Please where it says,

Course Duration
every other week for 8 weeks

Change to,

Course Duration: 8 weeks

Course format already says what will happen every other week, but they will still need to do stuff for the entire length of the 8 weeks

**Comment by dino-at-thegovlab** [comment]
just updated it directly in the yaml, but don't know how it will look

**Comment by claudioccm** [comment]
I will check that

**Comment by claudioccm** [comment]
done.
