### ISSUE TITLE
social media widgets for each program

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#25]
I don't really know what that means, but adding it to the list since Beth asked for them

**Comment by dino-at-thegovlab** [comment]
We also need these ASAP to start doing the promo.

**Comment by claudioccm** [comment]
@sahuguet was working on it.

**Comment by sahuguet** [comment]
Implemented using Carrot shared button.
https://github.com/carrot/share-button/wiki/Configuration-Options
