### ISSUE TITLE
Democracy Demo banner

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#33]
- add a feed to Democracy Demo at the bottom

**Comment by claudioccm** [comment]
is this a feed or a button? These are 2 completely different things.

**Comment by dino-at-thegovlab** [comment]
Whatever looks best for demo's? 

And the subscribe space to the digest.

**Comment by claudioccm** [comment]
Digest is already done. I split this issue in two, since they were 2 tasks. 
For the demos, I don't really like this idea, but whatever. I will figure out a way to insert the demos in this website.

**Comment by dino-at-thegovlab** [comment]
I think what beth wants is not the demos itself but the banner to the demos

**Comment by claudioccm** [comment]
that would be easier. Could you clarify that for me?
