### ISSUE TITLE
Make project gallery image oriented

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#38]
"What I see of the gallery now is all words. Will this be the case? Have always asked Claudio for these to be images. You click on the image and then it takes you to a description. Now it's endless text. 

We also have some nice visualizations that Luis created at the beginning of the term about our projects. We could use as a placeholder in lieu of gallery right now because this has to go out."

**Comment by dino-at-thegovlab** [comment]
@sahuguet 

@luisdaniel which viz is Beth talking about?

(quoted paragraph was written by Beth)

**Comment by sahuguet** [comment]
No idea.

On Tue, Jan 27, 2015 at 10:49 AM, Dinorah Cantú-Pedraza <
notifications@github.com> wrote:

> @sahuguet https://github.com/sahuguet
> 
> @luisdaniel https://github.com/luisdaniel which viz is Beth talking
> about?
> 
> (quoted paragraph was written by Beth)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/academy/issues/38#issuecomment-71670227.

## 

Arnaud Sahuguet
– Chief Technology Officer

**Comment by dino-at-thegovlab** [comment]
@claudioccm do you want me to buy a professional image for each project? something related to the key word of the project? and make the gallery look more like thetoolbox.org

or should I just google search for images? i'm concerned about copyright

or how do you imagine a more image-oriented gallery? i guess we have blank check as to how, since the only request from beth and the team in general is to make it more visually attractive. More images, less text. 

I can help to get whatever needed. We just need to decide on how to proceed.

**Comment by claudioccm** [comment]
@dino-at-thegovlab yeah, buying stock image for these projects would be the easier solution. Although I don't really believe this solution will result in a meaningful improvement. It will be visually better, for sure. 
Stealing images from google is not an option. There is also this website - http://www.freeimages.com/ - with free stock images. Not the best quality, but you get what you pay for, right?

**Comment by dino-at-thegovlab** [comment]
@claudioccm so what's the plan? add an image to each of the folders on the dropbox? add filename to the yaml? how will they be displayed so that I have a better idea of what images to look for

**Comment by claudioccm** [comment]
@dino-at-thegovlab - yep, that works. Add the images to the project folder, and add the filename to links > image in yaml. I added one example in your project, so you know how to proceed. You will notice that I did some small changes in the first 2 entries of the yaml file. This is a test, please don't change it. 

The images will work similar to the faculty member cards. I will use them as the header of the cards. For the detail view, I'm still not sure how I will do it, but I will figure something out.

**Comment by dino-at-thegovlab** [comment]
Think toolbox offers a good example: https://www.thetoolbox.org/tools

What I like:
- big picture
- small logo and big name
- starts the description but in super light gray and up to 100 characters

Then, when clicked... offers more images, maybe we could use that feature for the slide-deck?

**Comment by claudioccm** [comment]
I like this toolbox thing too. A few comments:
- Big Picture is Good. How are we on that? Do we already have the images?
- big name is good
- adding the logo to the list view is not a good idea. All the logos are terrible, so they will just make things worse. Will look like amateur stuff.
- 100 characters light description is good.

Once we have the images, I will re-do the list view in a way to reflect these ideas.

**Comment by dino-at-thegovlab** [comment]
Yes, big pictures are there since early morning.
