### ISSUE TITLE
graphic for coaching programs

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#39]
"For Coaching, can we include a graphic to show the pedagogy and to help the faculty know how to think about structure. To me, this encapsulates the process in a nutshell. This is a kind of mini timeline

T0 - Defining the Problem
T1 - Describing the Project
T2 - Engaging with People and Data
T3 - Measuring Impact
T4 - Persuading the Audience
T4+ - Prototype, Test, Evolve

Running underneath are three things you are always doing: Peer to Peer Coaching, Rapid Results Research, and Expert Mentoring. And there are swirls or circles (maybe like this http://hci.stanford.edu/dschool/resources/design-process/gallery.html#ideo) showing that it's all iterative.

This graphic will give both instructors and students a sense of the plan and the pedagogy. We can start with this graphic and I can turn that into a memo and how-to guide for folks."

**Comment by claudioccm** [comment]
do you understand this?
I saw the graphic from IDEO. It has several swirls. I have no idea how I should make the interconnections for this graph. Need more information on this.

This is what I have so far. I don't know which swirls connect to each circle. Any ideas?

![coaching-diagram](https://cloud.githubusercontent.com/assets/1649373/5926021/db567b22-a635-11e4-83de-f1f3a7c3af50.jpg)

**Comment by dino-at-thegovlab** [comment]
I think what Beth means is something that shows the process, but that throughout it, they will always have 3 components: Peer to Peer Coaching, Rapid Results Research, and Expert Mentoring

I imagine something like this (but please, I'm no designer, you can make it much nicer): 

![coaching program graphic](https://cloud.githubusercontent.com/assets/8558994/5931152/6b4cb940-a667-11e4-9250-4eb4766741a7.jpg)

Made it playing with photoshop:
https://drive.google.com/a/thegovlab.org/file/d/0B9P1gGvCmrkpSklhOWZYT1Z2R2s/view?usp=sharing

**Comment by dino-at-thegovlab** [comment]
Don't have to add the divergent, etc... just trying to make the point of what beth said "the iterative approach" or whatever.

**Comment by dino-at-thegovlab** [comment]
And maybe the colors of part of the "neck-tie" model can all be on the govlab purple

**Comment by dino-at-thegovlab** [comment]
Second experiment:

![coaching program graphic 2](https://cloud.githubusercontent.com/assets/8558994/5931509/c58edbc2-a66c-11e4-9b21-ab45e46843e9.jpg)

**Comment by dino-at-thegovlab** [comment]
Third experiment:

![coaching program graphic 3](https://cloud.githubusercontent.com/assets/8558994/5931649/400436e4-a66e-11e4-837a-c8164a64e03d.jpg)

**Comment by claudioccm** [comment]
done
