### ISSUE TITLE
landing page - concerns

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#44]
Hey, I'm looking at the latest snapshot for the landing page. Is this how it looks like? I have several concerns that I think are really important, since this is our first face and right now, is the thing that I dislike the most of the whole site. Just the beginning of it, the squares and how we work is cool. 
1. The info about the GovLab was supposed to go in the about section, not the landing page. Makes useless deleting the first paragraph because it was too much text to then just add more text... 
2. If we have a logo of the academy, why not use it? Instead of book icon that doesn't look very good with a regular font that spells out the academy.
3. Why 2 subscribe things? I think the stuff about the digest, needs to say, subscribe to the govlab digest, because is not clear enough for me to just have the name and the blank space. Don't know. 

This is what I looked at:

![screen shot 2015-01-27 at 9 51 36 pm 2](https://cloud.githubusercontent.com/assets/8558994/5931729/8c837a4c-a66f-11e4-9f93-e41eb416800f.png)

![screen shot 2015-01-27 at 9 51 54 pm 2](https://cloud.githubusercontent.com/assets/8558994/5931733/933ed78c-a66f-11e4-9e7e-94611e4d5323.png)

**Comment by dino-at-thegovlab** [comment]
Ok, now i get the the button says subscribe, so maybe that is clear enough

**Comment by dino-at-thegovlab** [comment]
But maybe the name, the govlab digest should become white if cursor over, and if clicked launch the latest digest edition on a separate tab? or at least add a square that explains what it is:

"A weekly curation of new findings and developments on innovation in governance."

**Comment by claudioccm** [comment]
I will leave the logo thing out of this issue. Gotta think more about it. The rest is done.
