### ISSUE TITLE
Coaching programs - Start date

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#74]
Chance everything that says...

Starts on (landing age for coaching programs and individual pages of coaching programs), to 

"Starts the week of: "

And then the dates have to be changed according to the week format. So they should go like this:
- February 16 - 20
- March 2 - 6
- March 16 - 20
- April 6 - 10

**Comment by claudioccm** [comment]
probably this will mess up the sorting.

**Comment by dino-at-thegovlab** [comment]
Can @sahuguet do something to fix it?

**Comment by claudioccm** [comment]
he said it will be fine
