### ISSUE TITLE
site takes too long to load

### ISSUE THREAD

**Issue by dino-at-thegovlab** [govlabacademy/govlabacademy.github.io#77]
@sahuguet the site takes too long to load... I'm not used to wait this long for any website and it messes with the design. It displays the coaches in a list instead of all grouped... when clicking to a coach it sends me to the top of the page and takes a while to load the specific coach info, etc... people will think it's not working and will hit the back button, before page finishes loading.

**Comment by claudioccm** [comment]
I think I know what is causing this.

**Comment by claudioccm** [comment]
I pushed a possible fix to this. 
@sahuguet - I switched the order of the RSS plugin. It was boing called before Isotopes. I think that the RSS plugin was responsible for the long load. Calling it after Isotopes, prevents Isotopes loading to be held by it. The cards are most visible loading problem. If this doesn't completely fix the problem, it should at least mitigate it. I hope it works

**Comment by dino-at-thegovlab** [comment]
Thank you! You are the best :)
