### ISSUE TITLE
fix share button placement

### ISSUE THREAD

**Issue by claudioccm** [govlabacademy/govlabacademy.github.io#87]

**Comment by sahuguet** [comment]
Now it is even further down.
Is it what you wanted?

On Sat, Jan 31, 2015 at 9:40 AM, Claudio Mendonca notifications@github.com
wrote:

> Closed #87 https://github.com/GovLab/academy/issues/87.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GovLab/academy/issues/87#event-227989499.

## 

Arnaud Sahuguet
– Chief Technology Officer
